# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aa892cfea2009f380bd4be568cbee39eca8743945f99ccb29a86481499d4e2c9ffcd2c02f3027dc1085b468ae4ca8d33b9f76cb3cdd97cefd1331c5559e90a0

test:
  secret_key_base: 94b5ee8578a2170842789c1b11ae44ae66b8917c5cdeea898b0528298ef1e92817acca3868ac6b152d420628bb702987ea5aee1a129d25ca60eff6e458eb79f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
